### ISSUE TITLE
GHC 7.8.4 cannot provide transformers 0.4.x

### ISSUE THREAD

**Issue by peti** [ivan-m/monad-levels#1]
It's a shame that GHC 7.8.4 cannot compile this package reliably because it depends on transformers 0.4.x, but transformers 0.3.x is a core library of the compiler and cannot be replaced. Maybe depending on `transformers-compat` instead would be an option to make this library more accessible for others?

**Comment by ivan-m** [comment]
I've written this using GHC 7.8.3 without any problems; is it truly a problem on 7.8.4?

Admittedly, I've been doing so in a sandbox.

**Comment by peti** [comment]
All 7.8.x versions of GHC ship transformers 0.3.x as a core library, so all of them will get into trouble once someone tries to link both the core and the non-core variant of transformers into the same binary. This happens, for instance, for packages that depend on `doctest`. Cabal will display a big, fat warning at configure time, saying that the binaries coming out of this build will most likely be broken.

**Comment by ivan-m** [comment]
Ahhh, gotcha.
